# The following section configures various pre-commit hooks to ensure code quality and consistency.

# Define repositories and their respective hooks
repos:
  # pre-commit-hooks repository contains a collection of git hooks for pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # The version of the pre-commit-hooks to use
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: check-added-large-files  # Prevents adding large files to the git repository
      - id: check-ast  # Validates Python abstract syntax trees
      - id: check-json  # Checks JSON file syntax
      - id: check-merge-conflict  # Checks for unresolved merge conflicts
      - id: check-xml  # Checks XML file syntax
      - id: check-yaml  # Checks YAML file syntax
      - id: debug-statements  # Checks for debug statements
      - id: end-of-file-fixer  # Ensures files end with a newline
      - id: mixed-line-ending
        args: ['--fix=auto']  # Automatically fixes line endings (can be set to 'lf' or 'crlf')

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.0
    hooks:
      - id: nbstripout
        files: ".ipynb"

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2  # Specify the desired version of Gitleaks
    hooks:
      - id: gitleaks

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
      - id: sqlfluff-lint
        # For dbt projects, this installs the dbt "extras".
        # You will need to select the relevant dbt adapter for your dialect
        # (https://docs.getdbt.com/docs/available-adapters):
        # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        # Arbitrary arguments to show an example
        # args: [--rules, "LT02,CP02"]
        # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']