Position	Players per position
Props	2
Hooker	1
Locks	2
Loose Forwards	3
Half Back	1
First Five-Eighth	1
Midfield	2
Back Three	3


Loose forwards are a combination of players who play as #8’s or flankers. You can select any combination of players for from these positions for this position, such as:

2x #8’s, 1x Flanker
2x Flankers, 1x #8
3x #8’s
3x Flankers


The Back Three is a combination of players who play as full backs or wingers. You can select any combination of players for from these positions for this position, such as:

1x Full Back, 2x Wingers
2x Wingers, 1x Full Back
3x Wingers
3x Full Backs
